# Generated by Django 4.0.5 on 2022-06-20 08:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_business_business_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='businessimage'),
        ),
    ]
